"""Compatibility imports for the shared weekly VIF-signal frame schema."""

from src.weekly_signal_schema import (
    ALIGNMENT_COLUMNS,
    ALIGNMENT_VECTOR,
    CORE_VALUES,
    N_ENTRIES,
    OVERALL_MEAN,
    OVERALL_UNCERTAINTY,
    PERSONA_ID,
    PERSONA_NAME,
    PROFILE_WEIGHT_COLUMNS,
    REQUIRED_WEEKLY_COLUMNS,
    UNCERTAINTY_COLUMNS,
    UNCERTAINTY_VECTOR,
    WEEK_END,
    WEEK_START,
    WEEKLY_SIGNAL_COLUMNS,
    alignment_col,
    profile_weight_col,
    uncertainty_col,
    validate_weekly_frame,
)

__all__ = [
    "ALIGNMENT_COLUMNS",
    "ALIGNMENT_VECTOR",
    "CORE_VALUES",
    "N_ENTRIES",
    "OVERALL_MEAN",
    "OVERALL_UNCERTAINTY",
    "PERSONA_ID",
    "PERSONA_NAME",
    "PROFILE_WEIGHT_COLUMNS",
    "REQUIRED_WEEKLY_COLUMNS",
    "UNCERTAINTY_COLUMNS",
    "UNCERTAINTY_VECTOR",
    "WEEK_END",
    "WEEK_START",
    "WEEKLY_SIGNAL_COLUMNS",
    "alignment_col",
    "profile_weight_col",
    "uncertainty_col",
    "validate_weekly_frame",
]
